import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import { apiLimiter, authLimiter } from './middleware/rateLimit.js';
import { notFound, errorHandler } from './middleware/error.js';
import authRoutes from './routes/auth.js';
import categoryRoutes from './routes/categories.js';
import productRoutes from './routes/products.js';
import imageRoutes from './routes/images.js';
import orderRoutes from './routes/orders.js';
import adminRoutes from './routes/admin.js';
import securityRoutes from './routes/security.js';
import healthRoutes from './routes/health.js';
import { env } from './config/env.js';
const app = express();
app.disable('x-powered-by'); app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: env.FRONTEND_ORIGIN, credentials: false, methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowedHeaders: ['Content-Type','Authorization','X-Monitor-Secret'] }));
app.use(express.json({ limit: '1mb' })); app.use(apiLimiter);
app.use('/api/auth', authLimiter, authRoutes);
app.use('/api/categories', categoryRoutes); app.use('/api/products', productRoutes); app.use('/api/images', imageRoutes);
app.use('/api/orders', orderRoutes); app.use('/api/admin', adminRoutes); app.use('/api/security', securityRoutes); app.use('/api/health', healthRoutes);
app.use(notFound); app.use(errorHandler);
export default app;
